### PR TITLE
Merge Sprint1 into master

### PR DESCRIPTION
**Pull request by mjosephwarren**
Complete Sprint1 (October 16 - October 22) by merging Sprint1 branch into master

**User Story 1: Basic Site and Framework**
- Angular framework setup @mjosephwarren  
- Basic design @angelavu 
- Movie objects @angelavu 
- Routing @mjosephwarren 

**User Story 1.1: Movie Display**
- Page to display movie information @benjaminvinicky 

**User Story 2: API Request for Data**
- API request to fetch data @benjaminvinicky 
- Populate movie object @benjaminvinicky 

**User Story 5: Customized Profiles**
- User profile page @jamesp21 
- Integrate profile editing for user @jamesp21 
- Privacy settings for user @jamesp21

### CODE REVIEW

**Review by angelavu — APPROVED** [review]
Looks great!

**Comment by benjaminvinicky** [comment]
good.

**Comment by jamesp21** [comment]
Approve

**Review by jamesp21 — COMMENTED** [review]
Good

**Pull request merged**
